project_id = "xsdlzoyaosfbbwzmcinq"

[functions.taxi-chat]
verify_jwt = false

[functions.taxi-voice]
verify_jwt = false

[functions.taxi-tts]
verify_jwt = false

[functions.taxi-stt]
verify_jwt = false

[functions.taxi-booking-webhook]
verify_jwt = false

[functions.taxi-realtime]
verify_jwt = false

[functions.taxi-realtime-gemini]
verify_jwt = false

[functions.taxi-extract]
verify_jwt = false

[functions.geocode]
verify_jwt = false

[functions.taxi-address-tts]
verify_jwt = false

[functions.taxi-trip-resolve]
verify_jwt = false
